# Generated by Django 2.0.2 on 2018-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('smoking', models.CharField(max_length=1)),
                ('BH', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BW', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allergy', models.CharField(max_length=1)),
                ('IgE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rhinosinusitis', models.CharField(max_length=1)),
                ('PFT', models.IntegerField()),
                ('FVC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FEV1', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
