# Generated by Django 2.0.2 on 2018-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asthma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='PAH',
            field=models.DecimalField(decimal_places=2, default='1.00', max_digits=5),
        ),
    ]
