# Generated by Django 2.0.2 on 2018-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asthma_app', '0003_auto_20180603_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='PAH',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
