# Generated by Django 2.0.2 on 2018-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asthma_app', '0004_auto_20180603_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='IgE',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
